### PR TITLE
Mouse wheel zoom bugfix

### PR DESCRIPTION
**Pull request by dudv**
Mouse wheel zooming is currently inverted. This change fixes it.

### CODE REVIEW

**Comment by dudv** [comment]
meow @pdubroy @thomasschiwietz

**Comment by pdubroy** [comment]
lgtm. I assume this matches the behavior of e.g. Google Maps?

**Comment by dudv** [comment]
Yes. Before it was inversed and @thomasschiwietz asked me to fix that.

**Comment by pdubroy** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pdubroy. Merge queue now has a length of 1.

**Pull request merged**
