### PR TITLE
Allow navigation in sdl viewer with num lock switched on.

### PR DESCRIPTION
**Pull request by feuerste**
This may make #286 obsolete?

### CODE REVIEW

**Comment by feuerste** [comment]
@schwoere FYI

**Comment by feuerste** [comment]
ptal @catevita

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user feuerste. Merge queue now has a length of 1.

**Pull request merged**
