### PR TITLE
updating clap version

### PR DESCRIPTION
**Pull request by catevita**
the error appears by using it in avmg. clippy does not seem to complain - yet

### CODE REVIEW

**Comment by catevita** [comment]
PTAL @feuerste

**Comment by catevita** [comment]
this prevents an error documented in https://github.com/TeXitoi/structopt/issues/157

**Comment by catevita** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user catevita. Merge queue now has a length of 1.

**Pull request merged**
