### PR TITLE
Refactor octree server to export grpc server

### PR DESCRIPTION
**Pull request by ksavinash9**
Refactor octree server. This will helps in:
* Making it extensible for integration testing
* Modularity which helps in building starting octree server from other packages

Needs to be tested with frustum query client.

### CODE REVIEW

**Comment by ksavinash9** [comment]
@SirVer please review.

**Comment by SirVer** [comment]
@ksavinash9 I think you need to merge master, but I am not sure.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
