### PR TITLE
Switch to using StructGenerator from glbindings

### PR DESCRIPTION
**Pull request by SirVer**
Instead of standalone functions, we now load the GL bindings into a struct. This should make it easier to move all opengl related functionality into one submodule, which again should make it simpler to swap it out against other functionality (e.g. WebGL).

### CODE REVIEW

**Comment by SirVer** [comment]
@thomasschiwietz rebased and updated. PTAL.

**Comment by SirVer** [comment]
@thomasschiwietz PTAL.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
