### PR TITLE
Double precision sdl viewer.

### PR DESCRIPTION
**Pull request by feuerste**
* Introduce f64 based vertex shader
* Depending on whether the octree data is f32 or f64, a different shader program is used
* Performance doesn't degrade, see profiling results:
  * **non-f64 octree:**
    * _current master:_
      FPS: 119.63, Drew 10227591 points from 391 loaded nodes. 1280 nodes should be shown, Cache 88.77618 MB
      FPS: 116.73, Drew 20016694 points from 817 loaded nodes. 1280 nodes should be shown, Cache 172.79672 MB
    * _this PR:_
      FPS: 124.42, Drew 9968449 points from 381 loaded nodes. 1280 nodes should be shown, Cache 86.55194 MB
      FPS: 123.10, Drew 20223557 points from 826 loaded nodes. 1280 nodes should be shown, Cache 174.57224 MB
  * **f64 octree:**
    * _current master:_
      FPS: 155.39, Drew 5330564 points from 244 loaded nodes. 1280 nodes should be shown, Cache 137.2578 MB
      FPS: 114.12, Drew 10701492 points from 406 loaded nodes. 1280 nodes should be shown, Cache 275.55493 MB
      FPS: 108.18, Drew 14424122 points from 530 loaded nodes. 1280 nodes should be shown, Cache 371.4097 MB
    * _this PR:_
      FPS: 252.95, Drew 8065945 points from 321 loaded nodes. 1280 nodes should be shown, Cache 207.69168 MB
      FPS: 226.52, Drew 16721513 points from 662 loaded nodes. 1280 nodes should be shown, Cache 430.5657 MB
        FPS: 236.18, Drew 25770872 points from 1099 loaded nodes. 1280 nodes should be shown, Cache 663.5795 MB

### CODE REVIEW

**Comment by SirVer** [comment]
Did you test on Mac and Linux?

**Comment by feuerste** [comment]
> Did you test on Mac and Linux?

Yes, it works on both Mac and Linux.

**Comment by feuerste** [comment]
@negin-z FYI

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user feuerste. Merge queue now has a length of 1.

**Pull request merged**
