### PR TITLE
Change to f64 projection matrix.

### PR DESCRIPTION
**Pull request by feuerste**
Currently when navigating an octree covering the earth, moving around feels like going in steps. This is due to the limited f32 resolution of the translational part of the projection matrix. This PR updates the matrix to an f64 based one, removing the "stuttering".

### CODE REVIEW

**Comment by catevita** [comment]
@wally-the-cartographer merge

**Comment by feuerste** [comment]
@catevita Can you please make sure that with this PR also the web server still works? Thank you!

**Comment by catevita** [comment]
> @catevita Can you please make sure that with this PR also the web server still works? Thank you!

the web server works, but we have to use a better bounding box for the camera

**Comment by feuerste** [comment]
> > @catevita Can you please make sure that with this PR also the web server still works? Thank you!
> 
> the web server works, but we have to use a better bounding box for the camera

Thanks @catevita 
By bounding box you mean initial pose?

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user feuerste. Merge queue now has a length of 1.

**Pull request merged**
