### PR TITLE
Support for XBox 360 controller (USB only).

### PR DESCRIPTION
**Pull request by SirVer**
Only tested on Mac.

You need to install a driver from here before this will work: 
https://github.com/360Controller/360Controller/releases

This is not very flexible and it could be that under Linux the scaling works differently so this does not feel nice. However, since this is only used for demos I did not feel like adding dynamic configuration for the scaling values of the different controllers into the code at this point in time.

### CODE REVIEW

**Comment by catevita** [comment]
the driver did get me goosebumps, i took the latest dmg and i had to reboot the mac several times before I could start it again.. do you suggest some version of the driver?

**Comment by SirVer** [comment]
I just used the latest one and it just worked for me.

There is no need to test code that you review, it is the author's responsibility to make sure the code is working.

**Comment by SirVer** [comment]
thanks for the review!

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by SirVer** [comment]
@cschuet Wally down again?

**Comment by gaschler** [comment]
Wally may be down in addition, but you have a build error

```
    Checking point_viewer_grpc v0.1.0 (/home/travis/build/googlecartographer/point_cloud_viewer/point_viewer_grpc)
error[E0308]: mismatched types
   --> sdl_viewer/src/lib.rs:321:20
    |
321 |         camera.pan(right, 0., forward);
    |                    ^^^^^ expected f64, found f32
help: you can cast an `f32` to `f64` in a lossless way
    |
321 |         camera.pan(right.into(), 0., forward);
    |                    ^^^^^^^^^^^^
```

**Comment by SirVer** [comment]
@gaschler Thanks! But it is down, otherwise it would have posted here that not all checks pass - at least my initial implementation of it did that.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Pull request merged**
