### PR TITLE
Bugfix for ECEF octrees: visible nodes traversal

### PR DESCRIPTION
**Pull request by catevita**
Nikolai found out that the tree traversal for visible nodes in ecef was not successful when an empty node was encountered. Here the correction.

### CODE REVIEW

**Comment by catevita** [comment]
PTAL @nnmm

**Comment by catevita** [comment]
PTAL @feuerste

**Comment by nnmm** [comment]
I took a second look and think the following accomplishes the fix in a cleaner way: https://github.com/googlecartographer/point_cloud_viewer/compare/nnmm/visible_nodes_bugfix

That way, we do one less hash map lookup. Feel free to cherry-pick it into the PR.

**Comment by catevita** [comment]
indeed! the latest solution you presented is also much more readable.

**Comment by nnmm** [comment]
:+1:

**Comment by catevita** [comment]
@nnmm if it was an approval it needs to be explicit

**Comment by catevita** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user catevita. Merge queue now has a length of 1.

**Pull request merged**
