### PR TITLE
Use criterion for benchmarks

### PR DESCRIPTION
**Pull request by nnmm**
With bencher, it was hard to get meaningful results:
* I couldn't find a way to increase the number of times a function is iterated, to get narrower error bars
* But that wouldn't help anyway because bencher reports the difference between the min and max as the error bar, so the error bar would only grow.

Criterion can be used like bencher (`cargo bench`) but has much nicer reporting. Sample output:

> Benchmarking bench_s2_building_singlethreaded: Warming up for 3.0000 s
> Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 828.6s or reduce sample count to 10.
> bench_s2_building_singlethreaded
>                         time:   [148.67 ms 149.33 ms 150.27 ms]
>                         change: [-6.5982% -3.3366% +0.3522%] (p = 0.06 > 0.05)
>                         No change in performance detected.
> Found 16 outliers among 100 measurements (16.00%)
>   14 (14.00%) high mild
>   2 (2.00%) high severe

As you can see, if you've run it before, it will compare the durations. It also does warmup runs, which helps decrease variance from disk caches.

### CODE REVIEW

**Comment by nnmm** [comment]
ptal @feuerste

**Comment by feuerste** [comment]
... and of course formatting needs to be fixed first :)

**Comment by nnmm** [comment]
True, it's heavy, but at least it's a dev-dependency. So if you do `cargo build` in any of the crates including `point_cloud_test`, it won't get built, only when doing `cargo test/bench` in that crate (or all crates via `--workspace`). Do you agree it's worth it?

**Comment by feuerste** [comment]
It's fine with me.

**Pull request merged**
