### PR TITLE
Update README.md for the point_cloud_viewer

### PR DESCRIPTION
**Pull request by spielawa**

### CODE REVIEW

**Comment by spielawa** [comment]
I signed it!

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 2.

**Pull request merged**
