### PR TITLE
Fix a potential overflow in FPS calculation

### PR DESCRIPTION
**Pull request by SirVer**
Master is crashing in debug mode when you look into black areas (nothing to draw) with:

`thread 'main' panicked at 'attempt to multiply with overflow', sdl_viewer/src/lib.rs:224:23`

This fixes this by hoisting an i32 into a floating point number earlier.

### CODE REVIEW

**Comment by feuerste** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user feuerste. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: PUT https://api.github.com/repos/googlecartographer/point_cloud_viewer/pulls/226/merge: 502 Server Error []

Log:
~~~
=> handle work item: PR 226 on googlecartographer/point_cloud_viewer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/point_cloud_viewer]
HEAD is now at f2ed23c Initialize bbox with first element (#225)
 $ git clean -fd [data/point_cloud_viewer]
 $ git checkout master [data/point_cloud_viewer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/point_cloud_viewer]
Already up to date.
 => Checking out SirVer/00_fix_overflow_on_frame_counter as local branch pr_226.
 $ git remote add SirVer git@github.com:SirVer/point_cloud_viewer.git [data/point_cloud_viewer]
fatal: remote SirVer already exists.
 $ git fetch SirVer [data/point_cloud_viewer]
 $ git branch --track pr_226 SirVer/00_fix_overflow_on_frame_counter [data/point_cloud_viewer]
Branch 'pr_226' set up to track remote branch '00_fix_overflow_on_frame_counter' from 'SirVer'.
 => Switching to branch pr_226.
 $ git reset --hard HEAD [data/point_cloud_viewer]
HEAD is now at f2ed23c Initialize bbox with first element (#225)
 $ git clean -fd [data/point_cloud_viewer]
 $ git checkout pr_226 [data/point_cloud_viewer]
Switched to branch 'pr_226'
Your branch is up to date with 'SirVer/00_fix_overflow_on_frame_counter'.
 $ git pull --force [data/point_cloud_viewer]
Already up to date.
 => merge master.
 $ git merge master [data/point_cloud_viewer]
Already up to date.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/point_cloud_viewer]
On branch pr_226
Your branch is up to date with 'SirVer/00_fix_overflow_on_frame_counter'.

nothing to commit, working tree clean
 $ git push --force SirVer HEAD:00_fix_overflow_on_frame_counter [data/point_cloud_viewer]
Everything up-to-date
 => Abandoning branch pr_226.
 => Switching to branch master.
 $ git reset --hard HEAD [data/point_cloud_viewer]
HEAD is now at 0ec7392 Merge branch 'master' into pr_226
 $ git clean -fd [data/point_cloud_viewer]
 $ git checkout master [data/point_cloud_viewer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_226 [data/point_cloud_viewer]
Deleted branch pr_226 (was 0ec7392).

~~~

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
