### PR TITLE
Adds a binary that serves octrees over gRPC

### LINKED ISSUE #53: Add a gRPC based server for serving point clouds

### PR DESCRIPTION
**Pull request by SirVer**
Extend sdl_viewer to be able to connect to the server.

Fixes #53.

### CODE REVIEW

**Comment by thomasschiwietz** [comment]
add go install to readme

**Comment by SirVer** [comment]
both done.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
