### PR TITLE
Added an abstraction for a quadtree.

### PR DESCRIPTION
**Pull request by SirVer**
Build on the octree abstraction, but much simpler.

Related to #90.

### CODE REVIEW

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 89 on googlecartographer/point_cloud_viewer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/point_cloud_viewer]
HEAD is now at 20f21a2 Store node meta data in-memory instead of disc (#87)
 $ git clean -fd [data/point_cloud_viewer]
 $ git checkout master [data/point_cloud_viewer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/point_cloud_viewer]
fatal: unable to access 'https://github.com/googlecartographer/point_cloud_viewer/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

~~~

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
