### PR TITLE
Improve testing by sorting by idx.

### PR DESCRIPTION
**Pull request by feuerste**

### CODE REVIEW

**Comment by nnmm** [comment]
That only works for 2^24 points, right? Could we have an assertion somewhere that we have no more than that number?

**Comment by feuerste** [comment]
It should even work for more than that, because I still use the old sorting logic in addition, so if we have multiple points with the same index, they will next be sorted by position.

**Comment by nnmm** [comment]
But the index will wrap around, and then point 2^24 + 1 will come after 0, right?

**Comment by nnmm** [comment]
For slightly-fuzzy equality checking, we'd also need to do explicit iteration through both vectors instead of zipping, right? I.e. if the indices of the current elements don't match, skip the element with the smaller index (and count how often we do that).

**Comment by feuerste** [comment]
> But the index will wrap around, and then point 2^24 + 1 will come after 0, right?

Yes, but it will be the same for both octree points and s2 points, so we will only run into problems after sorting, if points with common indices are again very close to each other.

**Comment by feuerste** [comment]
> For slightly-fuzzy equality checking, we'd also need to do explicit iteration through both vectors instead of zipping, right? I.e. if the indices of the current elements don't match, skip the element with the smaller index (and count how often we do that).

Yes, but since I found a seed which works now, I thought we could do this in another PR.

**Comment by feuerste** [comment]
Thanks for the review!

**Pull request merged**
