### PR TITLE
Fix for subsampling resulting in empty nodes

### PR DESCRIPTION
**Pull request by nnmm**
Subsampling would sometimes result in empty nodes, when there is a long chain of nodes with only one child, as you'd get with big bounding boxes. However, octree queries work by recursing into the octree, starting from the root node, and take nonexistence as an indication that no nodes exist below that points.

### CODE REVIEW

**Comment by nnmm** [comment]
ptal @SirVer

**Comment by nnmm** [comment]
fyi @feuerste @catevita

**Comment by SirVer** [comment]
I do not understand how there can be empty nodes. And if they are, I would rather fix this bug.

**Comment by nnmm** [comment]
@SirVer  The problem would arise when there was a chain  rABCDEFG, rABCDEFGH, rABCDEFGHI, rABCDEFGHI, rABCDEFGHIJ, rABCDEFGHIJK of nodes with only one child. One-eight of points would always get pushed up into the parent node, until at some point there was only one point being pushed into the parent node. That point would get pushed further up, because points to push up during subsampling were selected by taking the points index modulo 8, so the first point would always get subsampled – but even if it wasn't pushed up, the nodes above would be the empty ones instead. So emptiness is hard to avoid. This solution is not the only one, and probably not the fastest, but it works.

**Comment by SirVer** [comment]
We had an offline discussion about this and considered various alternatives. We came to the following conclusions:

While we had plenty of ideas how we can work around empty nodes in our current scheme, it feels that we need to eventually deal with them anyhow, because it is easy to construct cases where we will encounter them (e.g. merging octrees or ill distributed data).

We decided to go ahead and deal with empty nodes (i.e. going ahead with nikolai's approach), but put in some effort to prune empty nodes at the leaf of the octree at creation time.

**Comment by catevita** [comment]
LGTM! thanks for the fix, @feuerste the modification in node drawer is not needed anymore

**Comment by nnmm** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user nnmm. Merge queue now has a length of 1.

**Pull request merged**
