### PR TITLE
Pull down Color from sdl_viewer.

### PR DESCRIPTION
**Pull request by SirVer**
- Make it generic over its datatype.
- Add WHITE constant.

### CODE REVIEW

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by SirVer** [comment]
weird error on travis. Let's try again.

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
